# SHIFT+ALT+DOWN ARROR KEY DUPLICATES THE EXISTING LINE
#  TO THE NEXT LINE 


# CTRL+/ TO COMMENT OUT THINGS IN PYTHON

# HOLDING ALT AND CLICKING ON MULTIPLE LINE WHERE 
# WE WANT TO WRITE SOMETHINNG ACTIVATES MULTILINE
# WRITING FEATURE IN VS CODE SO YA ITS HELPFUL TO 
# WRITE THE SAME LINES THAT REPEAT NUMEROUS NUMBER 
# OF TIMES LOL HAHHAH

# IF WE HOLD THE ALT KEY ON A LINE AND PRESS THE ARROW UP OR 
# DOWN KEY THEN WE CAN SIMPLY MOVE THE LINE UP OR DOWN WHEREEVER
# WE WANT

'''
YOU CAN USE TRIPLE SINGLE QUOTES TO 
BEGIN A MULTILINE COMMENT IN VS CODE IN PYTHON
'''