# WRITE A PROGRAM IN PYTHON TO MAKE A GROCERY PRICE TRACKER
# USING LISTS IN PYTHON

# LETS CREATE A LIST NAMED PRICES AND 
# STORE ALL THE PRICES IN IT
prices=[150,370,269,587,349,12]

# NOW HERE WE HAVE TO REMOVE THE ITEMS WHOSE PRICE IS 
# GREATER THAN 500 RUPEES
# NOTE:DOUBT HERE ASK MAM
filtered_price=[price for price in prices if price<=500]
print(filtered_price)

# HERE WE HAVE USED INSERT METHOD TO INSERT A 
#  PRICE AT INDEX 2
filtered_price.insert(2,171)
print(filtered_price)

# WE HAVE USED SORT METHOD TO SORT THE PRICES OF GROCERIES
# IN ASCENDING ORDER
filtered_price.sort()
print(filtered_price)

# HERE WE HAVE PRINTED THE SUM OF THE PRICES IN THE
# GROCERY LIST
print(sum(filtered_price))
