# WRITE A PROGRAM TO --->
# -STORE STUDENT INFORMATION IN A TUPLE IN THE FORMAT(NAME,AGE,GRADE,NAME,AGE,GRADE)
# -COUNTS HOW MANY TIMES A PARTICULAR GRADE APPEARS 
# -FINDS THE INDEX OF THE FIRST OCCURENCE OF GRADE A
# -UPDATES THE TUPLE BY CHANGING ONE STUDENT'S GRADE
# (HINT-TUPLES ARE IMMUTABLE SO RECREATE THE TUPLE)

# WE HAVE STORED THE DATA...
students_info=("PRATYUSH",19,"A+","RAHUL",20,"A","VEDANT",19,"A")
print(students_info)

# WE HAVE USED .COUNT METHOD TO CHECK HOW MANY TIMES A GRADE HAS 
# BEEN SCORED BY THE STUDENTS
print(students_info.count("A"))

# HERE WE HAVE USED .INDEX FUNCTION TO CHECK THE FIRST 
# OCCURENCE OF GRADE "A"
print(students_info.index("A"))

# LETS CHANGE THE GRADE OF VEDANT FROM A TO A+....
info_list=list(students_info)
print(info_list)
info_list[8]="A+"
print(info_list)

students_info=tuple(info_list)
print(students_info)

# SO LEMME EXPLAIN WHAT I HAVE DONE ABOVE
# SINCE WE KNOW THAT TUPLES ARE IMMUTABLE
# THEREFORE I HAVE CONVERTED THE EXISTING TUPLE TO LIST AND
# THEN UPDATED THE REQUIRED VALUE AND THEN
# AGAIN CONVERTED IT INTO TUPLE...;-)