# WRITE A PROGRAM TO MAKE A TRAVEL ITINERARY USING 
# LISTS AND TUPLES IN PYTHON 

# LETS MAKE A LIST NAMED CITIES 
cities=["MUMBAI","GANGTOK","DEHRADUN"]

# WE ARE USIMG APPEND METHOD TO ADD TWO MORE CITIES
# IN THE TRAVEL ITERNARY
cities.append("PATNA")
cities.append("DARJEELING")
print(cities)

# HERE WE ARE USING REMOVE METHOD TO REMOVE
# A CITY FROM THIS LIST 
# PAISE KHATAM HOGYE XD
cities.remove("PATNA")
print(cities)

# NOW WE WILL CONVERT THIS LIST INTO TUPLE
cities_tuple=tuple(cities)
print(cities_tuple)

# SO NOW THE LIST IS CONVERTED INTO TUPLE AND NOW WE WILL USE 
# SLICING OF TUPLE TO PRINT THE FIRST,MIDDLE AND LAST CITIES OF 
# THE TRAVEL ITINERARY
print(cities_tuple[0:1]) #FIRST CITY OF THE TUPLE   
print(cities_tuple[1:3]) #MIDDLE CITIES OF THE TUPLE
print(cities_tuple[-1:]) #LAST CITY OF THE TUPLE