# USE REPL(READ EVALUATE PRINT LOOP)
#  TO PRINT THE TABLE OF 5

# FIRST OPEN WINDOWS TERMINAL AND WRITE PYTHON AND
#  THEN START PRINTING UR TABLE

# python 
# 5*1=5 
# 5*2=10
# 5*3=15 and so on 