# SO THIS IS AN EXTERNAL DOWNLOADED PIP OF 
# PYTHON TEXT TO SPEECH WHICH ANYONE CAN 
# DOWNLOAD AND USE 

import pyttsx3
engine = pyttsx3.init()
engine.say("hey there its my first external downloaded pip ")
engine.runAndWait()

# COMMENTS IN PYTHON CAN BE DONE BY CLICKING CTRL+/ 

# AND FOR MULTILINE COMMENTS LIKE DONE ABOVE
# WE CAN SELECT THE PART TO COMMENT OUT USING OUR MOUSE 
# AND THEN CLICK CTRL+/ AND U R GOOD TO GO