# WRITE A PROGRAM TO FIND THE REMAINDER WHEN TWO 
# NUMBERS ARE DIVIDED AND THE NUMBERS ARE 
# TO BE INPUT BY THE USER

a=int(input("ENTER A"))
b=int(input("ENTER B"))
print("A :",a)
print("B :",b)
print("THE REMAINDER WHEN WE DIVIDE THE NUMBERS :",a%b)

# IF THE INPUT CASE IS NOT MENTIONED THEN JUST TAKE ANY TWO NUMBERS

p=10
q=6
print("THE REMAINDER WHEN THESE TWO NUMBERS GETS DIVIDED IS :",p%q)
