a=int(input("ENTER THE NUMBER : "))
print("THE SQUARE OF THE ENTERED NUMBER IS : ",a*a)
print("THE SQUARE OF THE ENTERED NUMBER IS : ",a**2)
# BOTH THE ABOVE METHODS TO FIND THE SQUARE OF NUMBER
# IS RIGHT WE CAN EITHER WRITE a*a or a**2
# SIMILARLY IF WE WANT TO FIND CUBE OF A NUMBER
#  WE WILL WRITE a*a*a OR a***3 
# a****4 
# a****5 
# AND SO ON.....

# FOR FINDING SQUARE OR CUBE OR ANYTHING a^2 or ^3 or a^4 
# ARE NOT VALID 