# SO BEFORE STARTING LISTS AND TUPPLE
#  LETS DIFFERENTIATE BTW STRINGS AND LISTS

# SO THE BASIC DIFFERENCE WHICH WILL ANSWER ALL UR QUESTIONS 
# IS THAT
# LISTS ARE MUTABLE WHEREAS STRINGS ARE IMMUTABLE

friends=["APPLE","GRAPES","85.69","ROHIT SIR","INTERPRETOR",False]
print(friends[0])
friends[0]="SAKHARAM"
print(friends[0]) #UNLIKE STRINGS LISTS ARE MUTABLE
print(friends)
print(friends[4])
print(friends[5])
print(friends[1:5])