# CHECK THAT TUPLE TYPE CANNOT BE CHANGED IN PYTHON

a=(56,54,23,"PRATYUSH","MAHIK")
a[2]="PIKACHU"
# SO THIS CLEARLY GIVES AN ERROR IF 
# WE TRY TO CHANGE THE VALUE OF TUPLE

b=[56,23,98,"PRATYUSH","KUMAR"]
b[4]="MAHIK"
print(b)
# IF WE DO THE SAME OPERATION WITH LISTS 
# IT GETS CHAMGED AND NO ERROR POPS OUT


