# TUPLE IS AN IMMUTABLE DATA TYPE IN PYTHON PROGRAMMING LANGUAGE

# A TUPLE IS JUST LIKE A LIST ,BUT ITS IMMUTABLE WHICH MEANS ONE CREATED,WE CANNOT CHANGE IT

# THE MAJOR DIFFERENCE BETWEEN A LIST AND A TUPLE IS THAT 
# A LIST IS MUTABLE WHEREAS A TUPLE IS IMMUTABLE

a=(56,23,65,98,91,107)  #THIS IS AN EXAMPLE OF TUPLE IN PYTHON
print(type(a))

b=()                    #THIS IS AN EMPTY TUPLE
print(type(b))

c=(6)
print(type(c))          #NOW HERE IN THE OUTPUT WE CAN SEE THAT ITS 
                        # SHOWING IT AS CLASS INT

d=(2,)
print(type(d))          #SO TO CREATE A TUPLE WITH SINGLE CHARACTER IN IT
                        # WE HAVE TO USE A COMMA , SO THAT PYTHON RECOGNISES
                        # IT AS A TUPLE

# NOW THE QUESTION IS CAN WE CHANGE 
# ANY ELEMENT OF THE TUPLE GIVEN BELOW
f=("PRATYUSH",26,98,True,"MAHIK")
f[2]="89"
# THE SIMPLE ANSWER IS _________!!!!!!


# ANSWER IS NO!!!
# IT WILL SHOW ERROR 