s={1,16,32,16,16} 
print(s,type(s))

print(s.add(69))    #ADDS SINGLE ELEMENT TO SETS
print(s)
print(len(s))       #RETURNS THE LENGTH OF SET
print(s.remove(69)) #REMOVES THE ENTERED ELEMENT FROM THE SET  
print(s.pop())      #IN SETS POP RANDOMLY REMOVES AN ELEMENT FROM THE SET
                    #HENCE IN MY OPINION WE SHOULD JUST AVOID USING IT IN 
                    #OUR SET
print(s)

print(s.discard(999)) #SO THIS METHOD IS USED TO DISCARD A VALUE FROM 
                      #THE SET AND IF THE ENTERED VALUE IS NOT IN THE SET
                      # IT SIMPLY GIVES THE OUTPUT NONE  
print(s)

# THIS IS THE REASON WE SHOULD PREFER USING DISCARD METHOD IN SETS
#INSTEAD OF USING REMOVE METHOD WHICH GIVES ERROR IF ENTERED VALUE NOT  
# FOUND AND CAUSES INCONVENIENCE

(s.clear())         #CLEARS THE WHOLE SET
print(s)

# NOW LETS SEE THE CONCEPT OF UNION AND INTERSECTION.....!!!

set1={5,8,19,1,32}     #PRINTS THE VALUES OF BOTH THE SETS WITH NO REPETITION OF VALUES WHICH ARE COMMON IN BOTH THE SETS  
set2={1,4,5,8,36,98}   #PRINTS THE VALUES WHICH ARE COMMON IN BOTH THE SETS
print(set1.union(set2))
print(set1.intersection(set2))

