# CAN WE HAVE A SET WITH 18(int) AND "18"(str) AS A VALUE IN IT?
s=set()
s.add(18)
s.add("18")
print(s)

# ANSWER=YES WE CAN ADD 18 AS AN INTEGER VALUE AND 18 AS A STRING 
# VALUE IN THE SET
 
# ALSO AS WE KNOW THAT WE CAN STORE VALUES OF DIFFERENT DATA TYPES
# IN A SET 