# QUESTION-4
# SO TELL ME WHAT IS THE LENGTH OF THE SET ?

s=set()
s.add(20)
s.add(20.0)
s.add('20')
print(s)
print(len(s))

# AND HERE YOU ALSO THOUGHT THAT IT WILL RETURN THE LENGTH AS 3 BUT NO..
# THIS IS BECAUSE PYTHON TREATED 20 AND 20.0 AS SAME NUMBER 
# IRRESPECTIVE OF THEIR DATA TYPE 

# FOR EXAMPLE:IN PYTHON IF WE CHECK 1==1.0 
# THEN IT WILL RETURN TRUE SIMILARLY,
# IN THIS QUESTION 
# IT CHECKS 20==20.0 AND RETURNS 2 AND HENCE IN THE SET 
# 20 GETS PRINTED AND IT GIVES US THE LENGTH AS 2 



# QUESION-5

s={}
print(type(s))
# SO THIS IS AN EMPTY DICTIONARY AND NOT AN 
# EMPTY SET AS AN INTERVIEWER CAN TRICK YOU WITH THIS SMALL QUESTION  