# CREATE AN EMPTY DICTIONARY AND.ALLOW 4 FRIENDS TO ENTER 
# THEIR FAVOURITE LANGAUGE AS VALUE AND THEIR NAMES AS 
# KEYS.ASSUME THERE NAMES ARE UNIQUE

d={}

name= input("ENTER YOUR NAME :")
lang=input("ENTER YOUT FAV LANGUAGE :")

d.update({name:lang})
name= input("ENTER YOUR NAME :")
lang=input("ENTER YOUT FAV LANGUAGE :")

d.update({name:lang})
name= input("ENTER YOUR NAME :")
lang=input("ENTER YOUT FAV LANGUAGE :")

d.update({name:lang})
name= input("ENTER YOUR NAME :")
lang=input("ENTER YOUT FAV LANGUAGE :")

d.update({name:lang})
print(d)

# QUESSTION-7
# WHAT WILL HAPPEN IF THE NAME OF TWO FRIENDS ARE SAME
# WHAT CHANGE WILL YOU NOTICE IN THE OUTPUT OF THE PROGRAM

# ANSWER- SO IF THE NAME OF TWO KEYS/TWO FRIENDS ARE SAME 
# THEN THE NAME OF THAT FRIEND WILL BE PRINTED WHOSE NAME IS PRINTED
# AND UPDATED AT THE LAST WITH THE RESPECTIVE VALUE


# QUESTION-8
# SO WHAT WILL HAPPEN IF THE VALUES OF KEYS ARE SAME
# OR SAYING THAT TWO FRIENDS SAY THAT TEY BOTH HAVE COMMON 
# FAVOURITE PROGRAMMING LANGUAGE?
# ANSWER-NOTHING WILL HAPPEN BECAUSE THE KEYS OF THE SET 
# IS THE IDENTIFIER AND HENCE NO ISSUE WILL OCCUR