        # WHAT IS A SET IN PYTHON 
# ANSWER-A SET IS A COLLECTION OF NON REPETITIVE ELEMENTS

# SETS ARE UNORDERED
# SETS ARE UNINDEXED 
# THERE IS NO WAY TO CHANGE ITEMS IN SETS ALTHOUGH WE CAN ADD NEW ONES
# SETS CANNOT CONTAIN DUPLICATE VALUES

s={1,16,32,16,16}    #THIS IS AN EXAMPLE OF SET
print(type(s))
print(s)

# HOW TO MAKE AN EMPTY SET
s={}            #SO IF WE TRY TO MAKE AN EMPTY SET LIKE THIS WE 
                #WILL END UP MAKING AN EMPTY DICTIONARY 
print(type(s))

e=set()         #SO THIS IS HOW WE HAVE TO CREATE AN EMPTY SET
print(type(e))

f={98,23,1,5,6,"PRATYUSH"} #AS YOU CAN SEE THAT WE CAN INCLUDE DIFF. DATA TYPES IN SETS 
print(f,type(f))