# CAN U CHANGE THE VALUES INSIDE A LIST WHICH IS 
# CONTAINED IM A SET S?
s={8,7,12,"ABHI",[1,2]}
print(s)


# ANSWER-SO FIRS OF ALL THE SIMPE ANSWER IS THAT 
#1.) WE CANNOT INCLUDE A LIST INSIDE A SET 
#2.) SINCE SETS ARE UNINDEXED WE CANNOT CHANGE ANY VALUES IN 
# A SET SO FORGET ABOUT CHANING A LIST HAHAHAHA LOL....


# THE ANSWER PERPLEXITY AI GAVE ME 
# ----NO YOU CANNOT CHANGE THE VALUE INSIDE A LIST CONTAINED IN 
# A SET IN PYTHON.IN FACT YOU CANNOT EVEN HAVE A LIST AS AN ELEMENT IN A
# SET BECAUSE SETS IN PYTHON REQUIRE ALL THEIR ELEMENTS TO BE IMMUTABLE 
# AD HASHABLE.LISTS ARE MUTABLE AND NOT HASHABLE,SO CANNOOT BE ADDED TO
# A SET 