# WRITE A PROGRAM TO INPUT 8 NUMBERS FROM THE USER 
# AND DISPLAY ALL THE UNIQUE NUMBERS ONCE

s=set()

n1=input("ENTER THE FIRST NUMBER :")
(s.add(int(n1)))
n2=input("ENTER THE SECOND NUMBER :")
(s.add(int(n2)))
n3=input("ENTER THE THIRD NUMBER :")
(s.add(int(n3)))
n4=input("ENTER THE FOURTH NUMBER :")
(s.add(int(n4)))
n5=input("ENTER THE FIFTH NUMBER :")
(s.add(int(n5)))
n6=input("ENTER THE SIXTH NUMBER :")
(s.add(int(n6)))
n7=input("ENTER THE SEVENTH NUMBER :")
(s.add(int(n7)))

print(s)
print(sum(s))

# SO HERE IF YOU ARE THINKING WHY ARE WE WRITING INT FUNCTION 
# THE SIMPLE REASON IS THAT INPUT FUNCTION STORES THE VALUES AS STRING DATATYPE
# EITHER YOU STORE ANY WORD OR NUMBER 

# THATS WHY ITS NECESSARY TO CONVERT THE INPUT NUMBERS FROM STRING TO INT DATATYPE
# USING INT

# THIS WILL ALSO HELP US CARRY ARETHMETIC OPERATIONS ON THE SET 
# IF NEEDED