# WRITE A PROGRAM TO FIND WHETHER A USERNAME CONTAINS LESS THAN
#  10 CHARACTERS OR NOT......

username=input("ENTER THE USERNAME :")

if(len(username)<10):
    print("THE USERNAME CONTAINS LESS THAN 10 CHARACTERS")

else:
    print("THE USERNAME CONTAINS GREATER THAN 10 CHARACTERS")   