# WRITE A PROGRAM TO FIND OUT WHETHER A NUMBER IS A PRIME NUMBER OR NOT

# A NUMBER IS A PRIME NUMBER ONLY IF ITS GETTING DIVIDED BY 1 OR 
# THE NUMBER ITSELF..

n=int(input("ENTER THE NUMBER U WANT TO CHECK:"))

for i in range(2,n):
    if(n%1)==0:
        print("NUMBER IS NOT PRIME")
        break

