# # WHAT IS A FUNCTION?.....
# # FUNCTIONS ARE A GROUP OF STATEMENTS PERFORMING A SPECIFIC TASK
# # A FUNCTION CAN BE USED IN A PR0GRAM N NUMBER OF TIMES 

# # WHAT IS THE NEED OF FUNCTIONS IN A PROGRAM?.....
# # SO WHEN A PROGRAM GETS BIGGER IN SIZE AND ITS COMPLEXITY
# # GROWS,ITS DIFFICULT FOR A PROGRAM TO KEEP TRACK ON WHICH PIECE OF 
# # CODE IS DOING WHAT AND HERE COMES THE ROLE OF FUNCTIONS WHICH MAKES 
# # THE WORK OF PROGRAMMERS EASY...:-)


# # HERE IN THE EXAMPLE GIVEM BELOW
# ----------->FUNCTION DEFINATION<-----------
# def avg():
#     a=int(input("ENTER THE FIRST NUMBER :"))
#     b=int(input("ENTER THE SECOND NUMBER :"))
#     c=int(input("ENTER THE THIRD NUMBER :"))

#     average=(a+b+c)/3
#     print(average)

# avg()  -->#FUNCTION CALL<---
# avg()   # A FUNCTION CAN BE CALLED n NUMBER OF TIMES #
 

# def greet():
#     name=input("ENTER YOUR NAME:")
#     # text="GOOD MORNING"
#     print(f"A VERY GOODMORNING TO UHHH {name}!!! \n HOPE YOU HAVE A GOOD DAY AHEAD")

# greet()

