# WHAT IS PANDAS?
# PANDAS IS A PYTHON LIBRARY USED FOR WORKING WITH DATA SETS 
# IT HAS FUNCTIONS FOR ANALYZING,CLEANING,EXPLORING AND MANIPULATING DATA
# PANDAS IS USUALLY IMPORTED UNDER THE pd alias

# IT GIVES US ANSWERS AS 

# WHAT IS THE USE OF PANDAS?
# PANDAS ALLOWS US TO ANALYZE BIG DATA AND MAKE THEM READABLE AND RELEVANT AS 
# ITS VERY IMPORTANT IN DATA SCIENCE

import pandas as pd

mydataset={
    'cars':["BMW","VOLVO","FORD"],
    'passings':[3,7,2]
}
myvar=pd.DataFrame(mydataset)
print(myvar)
